# Generated by Django 4.1.7 on 2023-04-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doginfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed_name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('age', models.FloatField()),
                ('vaccine', models.CharField(max_length=40)),
                ('price', models.FloatField()),
            ],
        ),
    ]
