# Generated by Django 4.1.7 on 2023-09-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doginfo',
            name='uid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doginfo',
            name='age',
            field=models.FloatField(verbose_name='Months'),
        ),
        migrations.AlterField(
            model_name='doginfo',
            name='breed_name',
            field=models.CharField(max_length=30, verbose_name='Breed'),
        ),
        migrations.AlterField(
            model_name='doginfo',
            name='gender',
            field=models.CharField(choices=[('1', 'Male'), ('2', 'Female')], max_length=30, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='doginfo',
            name='price',
            field=models.FloatField(verbose_name='Quote'),
        ),
        migrations.AlterField(
            model_name='doginfo',
            name='vaccine',
            field=models.CharField(choices=[('1', 'Done'), ('2', 'Pending')], max_length=40, verbose_name='Vaccination'),
        ),
    ]
